// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookWEBAPI.WEB
{
    public partial class Books
    {
        public Books()
        {
            Rents = new HashSet<Rents>();
        }

        public int BookId { get; set; }
        public string BookTitle { get; set; }
        public string BookDescription { get; set; }
        public string BookAuthor { get; set; }
        public DateTime? BookReleaseDate { get; set; }

        public virtual ICollection<Rents> Rents { get; set; }
    }
}