// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookWEBAPI.WEB
{
    public partial class Complaints
    {
        public int ComplaintId { get; set; }
        public string ComplaintTitle { get; set; }
        public string ComplaintDescription { get; set; }
        public string ComplaintLocation { get; set; }
        public string ComplaintImagePath { get; set; }
        public string ComplaintStatus { get; set; }
        public int? UserId { get; set; }

        public virtual UsersTable User { get; set; }
    }
}