// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookWEBAPI.WEB
{
    public partial class Crimes
    {
        public int CrimeId { get; set; }
        public string CrimeTitle { get; set; }
        public string CrimeDescription { get; set; }
        public string CrimeImagePath { get; set; }
        public string CrimeLocation { get; set; }
        public string CrimeStatus { get; set; }
        public int? UserId { get; set; }

        public virtual UsersTable User { get; set; }
    }
}