// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookWEBAPI.WEB
{
    public partial class MissingPersons
    {
        public int MissingPersonId { get; set; }
        public string MissingPersonTitle { get; set; }
        public string MissingPersonDescription { get; set; }
        public string MissingPersonImagePath { get; set; }
        public string MissingPersonStatus { get; set; }
        public string MissingPersonLocation { get; set; }
        public int? UserId { get; set; }

        public virtual UsersTable User { get; set; }
    }
}