// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookWEBAPI.WEB
{
    public partial class Rents
    {
        public int RentId { get; set; }
        public int? BookId { get; set; }
        public int? UserId { get; set; }
        public byte[] RentDate { get; set; }

        public virtual Books Book { get; set; }
        public virtual UsersTable User { get; set; }
    }
}